# Generated by Django 4.1.1 on 2022-10-09 14:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_website_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='footer_menu',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='website',
            name='header_menu',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100))]))], blank=True, use_json_field=True),
        ),
    ]
