# Generated by Django 4.1.1 on 2022-10-09 16:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_website_footer_menu_website_header_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='footer_menu',
            field=wagtail.fields.StreamField([('link_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='header_menu',
            field=wagtail.fields.StreamField([('link_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100))]))], blank=True, use_json_field=True),
        ),
    ]
