# Generated by Django 4.1.1 on 2022-10-09 17:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_website_footer_menu_alter_website_header_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='footer_menu',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_external', wagtail.blocks.URLBlock(required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='header_menu',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_external', wagtail.blocks.URLBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
