# Generated by Django 4.1.1 on 2022-10-10 07:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_navigationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='header_menu',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Primary navigation', use_json_field=None),
        ),
        migrations.AlterField(
            model_name='website',
            name='footer_menu',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='header_menu',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
