# Generated by Django 4.1.1 on 2022-10-10 07:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_navigationsettings_header_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationsettings',
            old_name='header_menu',
            new_name='primary_navigation',
        ),
        migrations.RemoveField(
            model_name='website',
            name='footer_menu',
        ),
        migrations.RemoveField(
            model_name='website',
            name='header_menu',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='footer_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Small print text at the bottom of all pages. Not required.'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='footer_navigation',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Links at the bottom.', use_json_field=None),
        ),
    ]
