# Generated by Django 4.1.1 on 2022-10-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_header_menu_navigationsettings_primary_navigation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationsettings',
            old_name='footer_description',
            new_name='footer_text',
        ),
    ]
