# Generated by Django 4.1.1 on 2022-10-10 12:46

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_footer_description_navigationsettings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='featured_image',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(required=False))], label='Image', template='patterns/blocks/image_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='website',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
