# Generated by Django 4.1.1 on 2022-10-10 15:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_website_featured_image_website_heading_website_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='footer_navigation',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Links at the bottom.', use_json_field=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='primary_navigation',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Primary navigation', use_json_field=True),
        ),
    ]
