# Generated by Django 4.1.1 on 2022-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddocument',
            name='source',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
