# Generated by Django 4.1.1 on 2022-10-10 14:42

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_standarddocument_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddocument',
            name='description',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='Small print text at the bottom of all pages. Not required.'),
        ),
    ]
