# Generated by Django 4.1.1 on 2022-10-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_standarddocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddocument',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='standarddocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standarddocument',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
