# Generated by Django 4.1.1 on 2022-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_standarddocument_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarddocument',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
